***Heart Disease Research Part I, One Sample T-test, Binomial test***

In this project, you’ll investigate some data from a sample patients who were evaluated for heart disease at the Cleveland Clinic Foundation. The data was downloaded from the UCI Machine Learning Repository and then cleaned for analysis. 


First let's load data and investigate dataset

In [1]:
import pandas as pd
import numpy as np

# load data
heart = pd.read_csv('heart_disease.csv')
print(heart.head())

    age     sex  trestbps   chol                cp  exang  fbs  thalach  \
0  63.0    male     145.0  233.0    typical angina    0.0  1.0    150.0   
1  67.0    male     160.0  286.0      asymptomatic    1.0  0.0    108.0   
2  67.0    male     120.0  229.0      asymptomatic    1.0  0.0    129.0   
3  37.0    male     130.0  250.0  non-anginal pain    0.0  0.0    187.0   
4  41.0  female     130.0  204.0   atypical angina    0.0  0.0    172.0   

  heart_disease  
0       absence  
1      presence  
2      presence  
3       absence  
4       absence  


Let's split dataset into two subsets:

* yes_hd, which contains data for patients with heart disease
* no_hd, which contains data for patients without heart disease

For this project, we’ll investigate the following variables:

* chol: serum cholestorol in mg/dl
* fbs: An indicator for whether fasting blood sugar is greater than 120 mg/dl (1 = true; 0 = false)

In [3]:
yes_hd = heart[heart.heart_disease == 'presence']
no_hd = heart[heart.heart_disease == 'absence']
#1 Getting cholesterol for people with heart disease
chol_hd = yes_hd.chol

In general, total cholesterol over 240 mg/dl is considered “high” (and therefore unhealthy). Calculate the mean cholesterol level for patients who were diagnosed with heart disease and print it out. Is it higher than 240 mg/dl?

In [4]:
average_chol_yes_hd = np.mean(chol_hd)
print("Average cholesterol for people with heart disease in our dataset is {}".format(round(average_chol_yes_hd,1)))

Average cholesterol for people with heart disease in our dataset is 251.5


Do people with heart disease have high cholesterol levels (greater than or equal to 240 mg/dl) on average? Import the function from scipy.stats that you can use to test the following null and alternative hypotheses:

Null: People with heart disease have an average cholesterol level equal to 240 mg/dl
Alternative: People with heart disease have an average cholesterol level that is greater than 240 mg/dl
Note: Unfortunately, the scipy.stats function we’ve been using does not (at the time of writing) have an alternative parameter to change the alternative hypothesis for this test. Therefore, you’ll have to run a two-sided test. However, since you calculated earlier that the average cholesterol level for heart disease patients is greater than 240 mg/dl, you can calculate the p-value for the one-sided test indicated above simply by dividing the two-sided p-value in half.

Run the hypothesis test and print out the p-value. Can you conclude that heart disease patients have an average cholesterol level significantly greater than 240 mg/dl? Use a significance threshold of 0.05.

In [6]:
#Null Hypothesis: People with heart disease have an average cholesterol level equal to 240 mg/dl
from scipy.stats import ttest_1samp
tstat, pval = ttest_1samp(chol_hd, 240)
print("One sided p-value is {}, it is less than threshold 0.05 which indicates that an average cholesterol level is significantly higher than 240 mg/dl".format(round(pval/2,4)))

One sided p-value is 0.0035, it is less than threshold 0.05 which indicates that an average cholesterol level is significantly higher than 240 mg/dl


Repeat steps 1-4 in order to run the same hypothesis test, but for patients in the sample who were not diagnosed with heart disease. Do patients without heart disease have average cholesterol levels significantly above 240 mg/dl?

In [7]:
# Steps 1-4 for people without heart disease
chol_no_hd = no_hd.chol
average_chol_no_hd = np.mean(chol_no_hd)
print("Average cholesterol for people without heart disease in our dataset is {}".format(round(average_chol_no_hd,1)))
tstat, pval = ttest_1samp(chol_no_hd, 240)
print("One sided p-value is {}, it is more than threshold 0.05 which indicates that an average cholesterol level is not significantly higher than 240 mg/dl".format(round(pval/2,4)))

Average cholesterol for people without heart disease in our dataset is 242.6
One sided p-value is 0.264, it is more than threshold 0.05 which indicates that an average cholesterol level is not significantly higher than 240 mg/dl


Let’s now return to the full dataset (saved as heart). How many patients are there in this dataset? Save the number of patients as num_patients and print it out.

In [8]:
num_patients = len(heart)
print("{} patients in heart dataset".format(num_patients))

303 patients in heart dataset


Remember that the fbs column of this dataset indicates whether or not a patient’s fasting blood sugar was greater than 120 mg/dl (1 means that their fasting blood sugar was greater than 120 mg/dl; 0 means it was less than or equal to 120 mg/dl).

Calculate the number of patients with fasting blood sugar greater than 120.

In [11]:
num_highfbs_patients = np.sum(heart.fbs == 1)
print("There are {} patients with fasting blood sugar above 120 mg/dl".format(num_highfbs_patients))

There are 45 patients with fasting blood sugar above 120 mg/dl


Sometimes, part of an analysis will involve comparing a sample to known population values to see if the sample appears to be representative of the general population.

By some estimates, about 8% of the U.S. population had diabetes (diagnosed or undiagnosed) in 1988 when this data was collected. While there are multiple tests that contribute to a diabetes diagnosis, fasting blood sugar levels greater than 120 mg/dl can be indicative of diabetes (or at least, pre-diabetes). If this sample were representative of the population, approximately how many people would you expect to have diabetes? Calculate and print out this number.

Is this value similar to the number of patients with a resting blood sugar above 120 mg/dl — or different?

In [13]:
diabetes_per = (num_highfbs_patients/num_patients)*100
print("Percentage of patients with diabetes or pre diabetes based on fbs above 120 is {}%, which is almost two times higher than 8%".format(round(diabetes_per,1)))

Percentage of patients with diabetes or pre diabetes based on fbs above 120 is 14.9%, which is almost two times higher than 8%


Does this sample come from a population in which the rate of fbs > 120 mg/dl is equal to 8%? Import the function from scipy.stats that you can use to test the following null and alternative hypotheses:

Null: This sample was drawn from a population where 8% of people have fasting blood sugar > 120 mg/dl
Alternative: This sample was drawn from a population where more than 8% of people have fasting blood sugar > 120 mg/dl


Run the hypothesis test and print out the p-value. Using a significance threshold of 0.05, can you conclude that this sample was drawn from a population where the rate of fasting blood sugar > 120 mg/dl is significantly greater than 8%?

In [14]:
from scipy.stats import binom_test
p_value = binom_test(45, n=303, p =0.08, alternative = 'greater')
print("Given that pvalue for alternative hypothesis is {} and is less than 0.05 threshold we can conclude that this sample was drawn from a population where the rate of fbs > 120 mg/dl is significantly greater than 8%".format(p_value))

Given that pvalue for alternative hypothesis is 4.689471951448875e-05 and is less than 0.05 threshold we can conclude that this sample was drawn from a population where the rate of fbs > 120 mg/dl is significantly greater than 8%
